---
- name: Play for Install Nginx on WebServers
  hosts: localhost
  connection: local
  become: yes
  gather_facts: yes

  vars:
    custom_heading: "Welcome To Telugu AWS Training B43 By Sreeharsha Veerapalli - Autoscaling Testing"
    todays_date: "{{ ansible_facts['date_time']['date'] }}"
    host_name: "{{ ansible_facts['hostname'] }}"
    fqdn_name: "{{ ansible_facts['fqdn'] }}"
    ip_address: "{{ ansible_default_ipv4.address }}"

  tasks:
    - name: Run Apt Update
      apt:
        update_cache: yes

    - name: Install python3-apt
      apt:
        name: python3-apt
        state: present

    - name: Install Nginx Server
      apt:
        name: nginx
        state: present

    - name: Copy the files to index destination folder
      template:
        src: /myrepo/index.j2
        dest: /var/www/html/index.nginx-debian.html
        owner: root
        group: root
        mode: '0644'

    - name: Copy the style files to destination folder
      copy:
        src: /myrepo/style.css
        dest: /var/www/html/style.css
        owner: root
        group: root
        mode: '0644'

    - name: Copy the javascript files to destination folder
      copy:
        src: /myrepo/scorekeeper.js
        dest: /var/www/html/scorekeeper.js
        owner: root
        group: root
        mode: '0644'

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

