#!/bin/bash
#Use t2.micro. If you use t3.micro then the network interface should be ens5 in the playbook.
sudo apt update
sudo apt install software-properties-common -y
sudo apt-add-repository --yes --update ppa:ansible/ansible
sudo apt update
sudo apt install ansible -y
sudo apt install nginx -y
sudo apt-get install python3-apt -y
sudo apt install -y git stress
sudo git clone -b master https://github.com/azharshaik1872/ansibletesting.git ansible-aws-code
######GIVE ONLY ABOVE IN THE USER DATA FOR AMI IMAGE FOR AWS AUTOSCALING##########
#
#####GIVE BELOW IN THE LAUNCH CONFIG USERDATA#####################################
ansible-playbook /ansible-aws-code/playbook.yaml

######GIVE BELOW IN THE CUSTOM DATA OF AZURE VMSSS################################
#cloud-config
package_upgrade: true
packages:
  - jq

runcmd:
  - ansible-playbook /ansible-aws-code/playbook.yaml
